[build]
  command = "pnpm run build"
  publish = ".next"

[functions]
  directory = "src/pages/api"

[functions."*"]
  node_bundler = "esbuild"
  external_node_modules = ["pdf-parse", "helia", "openai", "node-fetch"]
  region = "eu-central-1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
